// app/Views/Dashboard.vue
<template>
  <div>
    <Header></Header>

    <TableCards v-bind="{members, cardMode, isOpen, highest, lowest, remove}"></TableCards>

    <Sidebar></Sidebar>

    <div v-if="members.length !== 0">
      <button
        class="a-btn a-btn--center"
        v-bind:class="{'a-btn--active': isOpen}"
        v-on:click="handleResolve"
      >{{ isOpen ? 'Hide Cards' : 'Show Cards'}}</button>
    </div>

    <div v-if="!team" class="a-not-set">
      <p>You have not yet created or selected a team.</p>
      <router-link class="a-btn" :to="{ name: 'home', params: { tab: 'create' } }">Create Team</router-link>
    </div>
    <p class="a-not-set" v-else-if="members.length === 0">No members here at the moment.</p>
  </div>
</template>

<script>
import TableCards from "../Components/TableCards";
import Sidebar from "../Components/Sidebar";
import Header from "../Components/Header";
import { mapState } from "vuex";

export default {
  name: "dashboard",
  components: {
    Sidebar,
    TableCards,
    Header
  },
  computed: mapState(["user", "team", "members", "cardMode"]),
  data() {
    return {
      error: "",
      isOpen: false,
      lowest: "",
      highest: ""
    };
  },
  methods: {
    addToStats(stats, card) {
      let alreadySet = false;

      stats.forEach(item => {
        if (item.label === card) {
          item.count++;
          alreadySet = true;
        }
      });

      if (!alreadySet) {
        stats.push({ label: card, count: 1 });
      }
    },
    setStats() {
      let lowest = "";
      let highest = "";
      let stats = [];

      this.members.forEach(member => {
        if (member && member.card === "") return;

        this.addToStats(stats, member.card);

        if (!lowest && !highest) {
          lowest = member.card;
          highest = member.card;
        } else if (member.card < lowest) {
          lowest = member.card;
        } else if (member.card > highest) {
          highest = member.card;
        }
      });

      this.lowest = lowest;
      this.highest = highest;

      return stats;
    },
    handleResolve() {
      this.isOpen ? this.clear() : this.resolve();
    },
    resolve() {
      this.isOpen = true;
      const stats = this.setStats();

      this.$store.dispatch("updateTeam", { team: this.team, isLocked: true });

      const getColor = number => {
        if (number === this.highest) return "rgba(222,91,73,1)";
        else if (number === this.lowest) return "rgba(70,178,157,1)";
        else return "rgba(7,134,216,1)";
      };
    },
    clear() {
      this.members.forEach(user => {
        user &&
          this.$store.dispatch("updateUser", { user: user.name, card: "" });
      });
      this.$store.dispatch("updateTeam", { team: this.team, isLocked: false });
      this.isOpen = false;
    },
    remove(user) {
      if (user === window.localStorage.getItem("user")) {
        if (window.confirm("Do you want to remove yourself from the team?")) {
          this.$store.dispatch("removeUserFromTeam", {
            team: this.team,
            user: this.user
          });
        }
      } else {
        this.$store.dispatch("removeUserFromTeam", {
          team: this.team,
          user: this.user
        });
      }
    }
  }
};
</script>

<style lang="scss">
@import "../styles/variables";

.title {
  text-align: left;
}

.chart {
  float: left;
  width: 25%;
  margin-top: 65px;
}
</style>

// pages/[teamId]/dashboard.tsx
import { NextPage } from 'next';
import { useEffect, useState } from 'react';
import { api } from '../../components/api';
import { Member, useMembers } from '../../components/apiHooks';
import { Button } from '../../components/elements/Button';
import { Loading } from '../../components/elements/Loading';
import { Header } from '../../components/Header';
import { Sidebar } from '../../components/Sidebar';
import { TableCards } from '../../components/TableCards';

type Statistic = {
  label: string;
  count: number;
};

const Dashboard: NextPage = () => {
  const [isOpen, toggleIsOpen] = useState(false);
  const [team, setTeam] = useState('');
  const [lowest, setLowest] = useState('');
  const [highest, setHighest] = useState('');
  // const [members, setMembers] = useState<Member[]>([]);
  const [cardMode, setCardMode] = useState('');

  const [members, isLoading] = useMembers(team);

  useEffect(() => {
    const myTeam = localStorage.getItem('teamId');

    if (!myTeam) return;

    setTeam(myTeam);
  }, []);

  const handleResolve = () => {
    isOpen ? clear() : resolve();
  };

  const addToStats = (stats: Statistic[], card: string) => {
    let alreadySet = false;

    stats.forEach((item) => {
      if (item.label === card) {
        item.count++;
        alreadySet = true;
      }
    });

    if (!alreadySet) {
      stats.push({ label: card, count: 1 });
    }
  };

  const setStats = () => {
    let lowest = '';
    let highest = '';
    const stats: Statistic[] = [];

    members &&
      members.forEach((member) => {
        if (member && member.card === '') return;

        addToStats(stats, member.card);

        if (!lowest && !highest) {
          lowest = member.card;
          highest = member.card;
        } else if (member.card < lowest) {
          lowest = member.card;
        } else if (member.card > highest) {
          highest = member.card;
        }
      });

    setLowest(lowest);
    setHighest(highest);

    return stats;
  };

  const resolve = () => {
    toggleIsOpen(true);
    // const stats = this.setStats();

    api.updateTeam(team, { isLocked: true });

    const getColor = (number: string) => {
      if (number === highest) return 'rgba(222,91,73,1)';
      else if (number === lowest) return 'rgba(70,178,157,1)';
      else return 'rgba(7,134,216,1)';
    };
  };

  const clear = async () => {
    // todo: add await
    members &&
      members.forEach((member) => {
        api.updateMember(team, member.name, { card: '' });
      });
    await api.updateTeam(team, { isLocked: false });
    toggleIsOpen(false);
  };

  const remove = async (member: Member) => {
    if (member.name === window.localStorage.getItem('member')) {
      if (window.confirm('Do you want to remove yourself from the team?')) {
        await api.removeMember(team, member.name);
      }
    } else {
      await api.removeMember(team, member.name);
    }
  };
  return (
    <>
      <Header />

      <Sidebar />

      {isLoading ? (
        <Loading />
      ) : (
        members && (
          <TableCards
            members={members}
            cardMode={cardMode}
            isOpen={isOpen}
            highest={highest}
            lowest={lowest}
            onRemove={remove}
          />
        )
      )}

      {!isLoading && members && members.length > 0 && (
        <Button variant='solid' isActive={isOpen} onClick={handleResolve}>
          {isOpen ? 'Hide Cards' : 'Show Cards'}
        </Button>
      )}

      {!team && (
        <div className='a-not-set'>
          <p>You have not yet created or selected a team.</p>
        </div>
      )}

      {members?.length === 0 && (
        <p className='a-not-set'>No members here at the moment.</p>
      )}
    </>
  );
};

export default Dashboard;
