// app/Components/Tabs.vue
<template>

    <section class="c-tabs">

        <div>
            <div class="c-tabs__list">
                <button class="c-tabs__item" v-for="(option, index) in options" :tabindex="index"
                        v-on:click="option.action"
                        v-bind:key="{index}"
                        v-bind:class="{'c-tabs__item--active' : isActive === option.name}">
                    {{option.name}}
                </button>
            </div>

            <section v-show="isActive === options.create.name">
                <form class="c-tabs__form" v-on:submit.prevent="onCreateTeam">
                    <input class="c-tabs__form__input" type="text" v-model="team" :ref="options.create.name" placeholder="Team Name"/>
                    <input class="c-tabs__form__input" type="submit" value="Create">
                    <p class="c-tabs__error" v-if="error">{{error}}</p>
                </form>
            </section>

            <section v-show="isActive === options.select.name">
                <form class="c-tabs__form" v-on:submit.prevent="onSelectTeam">
                    <input class="c-tabs__form__input" type="text" v-model="team" :ref="options.select.name" placeholder="Team Name"/>
                    <input class="c-tabs__form__input" type="submit" value="Select">
                    <p class="c-tabs__error" v-if="error">{{error}}</p>
                </form>
            </section>

        </div>

        <section v-show="isActive === options.join.name">
            <form class="c-tabs__form" v-on:submit.prevent="onJoinTeam">
                <input class="c-tabs__form__input" type="text" v-model="team" :ref="options.join.name" placeholder="Team Name"/>
                <input class="c-tabs__form__input" type="text" v-model="user" placeholder="User Name"/>
                <input class="c-tabs__form__input" type="submit" value="Join">
                <p class="c-tabs__error" v-if="error">{{error}}</p>
            </form>
        </section>

    </section>
</template>

<script>
    import fs, {api} from '../firestore';

	export default {
		name: "tabs",
		props: ['sharedState'],
		data() {

			return {
				isActive: '',
                user: '',
                error: '',
				options: {
					create: {
						name: 'Create',
						action: this.onCreate
					},
					select: {
						name: 'Select',
						action: this.onSelect
					},
					join: {
						name: 'Join',
						action: this.onJoin
					}
				}
			}
		},
		methods: {

			onCreate() {
				this.selectAndfocus(this.options.create);
			},

			onSelect() {
				this.selectAndfocus(this.options.select);
			},

			onJoin() {
				this.team = this.sharedState.team;
				this.selectAndfocus(this.options.join);
			},

			selectAndfocus(item) {
				this.isActive = item.name;
				this.error = '';
				this.$nextTick(() => this.$refs[item.name].focus());
			},

			onCreateTeam() {
				api.getTeam(this.team).then((teamDoc) => {

					if (teamDoc.exists) {
						this.error = "Team already exists";
						return;
					}

					this.sharedState.team = this.team;
					api.setTeam(this.team).then(() => {
						this.$router.push({name: 'dashboard'});
					}).catch(err => console.error('onCreateTeam() => setTeam()', err));
				}).catch(err => console.error('onCreateTeam() => getTeam()', err));
			},

			onSelectTeam() {
				api.getTeam(this.team).then((teamDoc) => {

					if (!teamDoc.exists) {
						this.error = "Team doesn't exists";
						return;
					}

					this.sharedState.team = this.team;
					this.$router.push({path: 'dashboard'});

				}).catch(err => console.error('onSelectTeam() => getTeam()', err));
			},

			onJoinTeam() {
				api.getTeam(this.team).then((teamDoc) => {

					if (!teamDoc.exists) {
						this.error = "Team doesn't exist";
						return;
					}

					this.$router.push({path: 'play'});

					this.sharedState.team = this.team;
					this.sharedState.user = this.user;
					const userCollection = api.getMembers(this.team);
					const users = userCollection.doc(this.user);

					users.onSnapshot((docs) => {
						const data = docs.data();
						this.card = data.card;
						this.activeCard = this.card;
					});

					users.set({name: this.user}).then(() => {
						this.isJoin = false;
						this.isUserSet = true;
						this.isTeamSet = true;
					}).catch(err => console.error('onJoinTeam() => users.set()', err));
				}).catch(err => console.error('onJoinTeam() => getTeam()', err));
			},

			onResetTeam() {
				this.team = '';
				this.handleResetTeam();
			}
        },
        mounted() {

            if(this.$route.params.tab === 'select')
                this.selectAndfocus(this.options.select);
            else if(this.$route.params.tab === 'join') 
                this.selectAndfocus(this.options.join);
            else 
                this.selectAndfocus(this.options.create);
        }
	}
</script>

<style lang="scss">

    @import '../styles/variables';
    @import '../styles/base';

    .c-tabs {
        text-align: center;

        &__item {    
            font-size: 18px;
            margin: 0 0.5rem;
            padding: 1rem;
            border: none;
            max-width: 30%;
            background-color: $light;
            color: white;
            transition: background-color 0.25s ease-in-out;
            cursor: pointer;

            &:focus {
                outline: none;
            }

            &--active {
                background-color: $dark;
                color: white;
            }

            @media (min-width: 672px) {
                font-size: 24px;
                min-width: 160px;
            }
        }

        &__link {
            color: $grey;
        }

        &__error {
            color: $red;
        }
        
        &__form {
            background-color: #324D5C;
            padding: 2rem;
            max-width: 900px;
            margin: 0 auto;

            &__input {
                background: transparent;
                border: none;
                border-bottom: 1px solid $grey;
                padding: 1rem;
                font-size: 24px;
                display: block;
                margin: 0 auto;
                margin-bottom: 1rem;
                color: white;
                -webkit-appearance: none;

                &:focus {
                    outline: none;
                }

                &[type="submit"] {
                    @extend .a-btn;
                    margin: 0 auto 1rem auto !important;
                }

                &::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
                    color: #20323c;
                }

                &:-ms-input-placeholder { /* Internet Explorer 10-11 */
                    color: #20323c;
                }

                &::-ms-input-placeholder { /* Microsoft Edge */
                    color: #20323c;
                }

            }
        }
    }

</style>

// components/Tabs.tsx
import styled from '@emotion/styled';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import { api } from './api';
import { Button } from './elements/Button';
import { Flex } from './elements/Flex';
import { Modal } from './Modal';
import Dropdown, { Option } from 'react-dropdown';
import 'react-dropdown/style.css';

const CARD_MODE_OPTIONS = [
  { value: 'fibonacci', label: 'Fibonacci' },
  { value: 'tshirt', label: 'T-Shirt' },
];

export const Tabs = () => {
  const [team, setTeam] = useState('');
  const [teamId, setTeamId] = useState('');
  const [member, setMember] = useState('');
  const [cardModeOption, setCardModeOption] = useState<Option>(
    CARD_MODE_OPTIONS[0]
  );
  const [error, setError] = useState('');

  const router = useRouter();

  const [showStartModal, setShowStartModal] = useState(false);
  const [showJoinModal, setShowJoinModal] = useState(false);

  const onCreateTeam = async (ev: React.FormEvent) => {
    ev.preventDefault();

    const teamId = await api.setTeam(team, cardModeOption.value);
    await api.setMember(teamId, member);

    localStorage.setItem('teamId', teamId);
    localStorage.setItem('member', member);

    router.push(`${teamId}/dashboard`);
  };

  const onJoinTeam = async (ev: React.FormEvent) => {
    ev.preventDefault();

    const myTeam = await api.getTeam(teamId);

    if (!myTeam.data()) {
      setError('Uuh ooh, Team does not exist');
      return;
    }

    const res = await api.setMember(teamId, member);

    if (res?.error) {
      setError(res.error);
      return;
    }

    localStorage.setItem('teamId', teamId);
    localStorage.setItem('member', member);

    router.push(`${teamId}/play`);
  };

  return (
    <>
      <Flex css={{ alignItems: 'center' }} gap={4}>
        <Button variant='solid' onClick={() => setShowStartModal(true)}>
          Start New Game
        </Button>
        <Button variant='link' onClick={() => setShowJoinModal(true)}>
          Join Game
        </Button>
      </Flex>

      {showStartModal && (
        <Modal
          title='Start a new game'
          handleClose={() => setShowStartModal(false)}
        >
          <TabForm onSubmit={onCreateTeam}>
            <Flex gap={12} css={{ alignItems: 'center' }}>
              <TabFormInput
                type='text'
                value={team}
                placeholder='Team Name'
                onChange={(ev) => setTeam(ev.currentTarget.value)}
              />
              <TabFormInput
                type='text'
                value={member}
                placeholder='Member Name'
                onChange={(ev) => setMember(ev.currentTarget.value)}
              />
              <Flex gap={8}>
                <Label>Card Deck</Label>
                <StyledDropdownd
                  options={CARD_MODE_OPTIONS}
                  onChange={(option) => setCardModeOption(option)}
                  value={cardModeOption}
                  placeholder='Select an option'
                />
              </Flex>
              <Button variant='solid' type='submit' onClick={onCreateTeam}>
                Start Game
              </Button>
            </Flex>
            {error && <ErrorText>{error}</ErrorText>}
          </TabForm>
        </Modal>
      )}

      {showJoinModal && (
        <Modal title='Join a game' handleClose={() => setShowJoinModal(false)}>
          <TabForm onSubmit={onJoinTeam}>
            <Flex gap={12} css={{ alignItems: 'center' }}>
              <TabFormInput
                type='text'
                value={teamId}
                placeholder='Team ID'
                onChange={(ev) => setTeamId(ev.currentTarget.value)}
              />
              <TabFormInput
                type='text'
                value={member}
                placeholder='Member Name'
                onChange={(ev) => setMember(ev.currentTarget.value)}
              />

              <Button variant='solid' type='submit' onClick={onJoinTeam}>
                Join Game
              </Button>
            </Flex>
            {error && <ErrorText>{error}</ErrorText>}
          </TabForm>
        </Modal>
      )}
    </>
  );
};

export const Title = styled.h2`
  font-size: 32px;
`;

export const Label = styled.label`
  color: white;
`;

export const StyledDropdownd = styled(Dropdown)`
  .Dropdown-control {
    min-width: 250px;
    border-radius: 8px;
  }
`;

const TabItem = styled.button<{ isActive: boolean }>`
  font-size: 18px;
  margin: 0 0.5rem;
  padding: 1rem;
  border: none;
  max-width: 30%;
  background-color: ${({ theme, isActive }) =>
    isActive ? theme.colors.blue : theme.colors.green};
  color: white;
  transition: background-color 0.25s ease-in-out;
  border-radius: 8px 8px 0 0;
  cursor: pointer;

  &:focus {
    outline: none;
  }

  @media (min-width: 672px) {
    font-size: 24px;
    min-width: 160px;
  }
`;

const ErrorText = styled.p`
  color: ${({ theme }) => theme.colors.red};
`;

const TabForm = styled.form`
  border-radius: 8px;
  max-width: 900px;
  margin: 0 auto;
`;

const TabFormInput = styled.input`
  background: transparent;
  border: 1px solid white;
  border-radius: 8px;
  padding: 1rem;
  font-size: 16px;
  display: block;
  color: white;
  min-width: 250px;

  -webkit-appearance: none;

  &:focus {
    outline: none;
    border: 1px solid ${({ theme }) => theme.colors.green};
  }

  &::placeholder {
    /* Chrome, Firefox, Opera, Safari 10.1+ */
    color: 'white';
  }

  &:-ms-input-placeholder {
    /* Internet Explorer 10-11 */
    color: #20323c;
  }

  &::-ms-input-placeholder {
    /* Microsoft Edge */
    color: #20323c;
  }
`;
